### ISSUE TITLE
Failed generating data, no level data found

### ISSUE THREAD

**Issue by damienfayet** [joffreybesos/d2r-mapview#10]
Hello,

I encounter an issue using d2r-mapview.

I manage to get map data (and the image is showing when reaching locahost server) but just after sending map data the server close with the following error :

/app/build/data/getMapData.js:152
                        throw new Error("Failed generating data, no level data found");
                              ^

Error: Failed generating data, no level data found
    at /app/build/data/getMapData.js:152:31
    at step (/app/build/data/getMapData.js:33:23)
    at Object.next (/app/build/data/getMapData.js:14:53)
    at fulfilled (/app/build/data/getMapData.js:5:58)

Same behavior with another seed / difficluty/id parmeters
Same behavior running it from my docker image or running it through server.sh
Any idea on how to fix it ?

**Comment by joffreybesos** [comment]
Ok that error means the executable that scrapes data from D2 LoD using wine has failed. It returned no map data.

The only things I think could cause this would be:
- There's a problem with your D2 LoD files
- You have requested invalid data (there's not much input validation)

In your cache folder there should be a `wineerrors.log` what does that say? It's ok if it has errors, but it might give a clue.

This error happens even if you access this URL in your browser? [http://localhost:3002/v1/map/12345/2/117/image](http://localhost:3002/v1/map/12345/2/117/image)

Double check you are sending a valid seed, difficulty and mapid.

Have you tried step 6 of the server troubleshooting? https://github.com/joffreybesos/d2r-mapview/blob/master/SERVER.md#troubleshoot
That is how you diagnose problems with wine generating data. It bypasses the server and directly generates map data.

**Comment by damienfayet** [comment]
- wineerrors.log is here but empty
- Step 6 of troubleshooting is working fine, i got data from maps
- i.e : http://localhost:3002/v1/map/12345/1/1 is returning data :
{"type":"map","id":1,"name":"Rogue Encampment","offset":{"x":5520,"y":5880}," ....

and after returning the data the container crashes 👍 
log of container : 

`[13.01.2022 17:02.55.092] [LOG]   Running on http://0.0.0.0:3002

[13.01.2022 17:03.04.762] [LOG]   New request for data 12345 1 1...

[13.01.2022 17:03.04.763] [LOG]   Getting single map 1

[13.01.2022 17:03.04.764] [LOG]   Spawning process: bin/d2-map.exe game --seed 12345 --difficulty 1 --map 1

[13.01.2022 17:03.06.379] [LOG]   Wine done generation 12345 1 1, took 1614ms

[13.01.2022 17:03.06.383] [LOG]   Generated single map data 12345 1, took 1620ms

[13.01.2022 17:03.06.384] [LOG]   Spawning process: bin/d2-map.exe game --seed 12345 --difficulty 1

[13.01.2022 17:03.06.387] [LOG]   Generated JSON for map 1 'Rogue Encampment', took 1625ms total

/app/build/data/getMapData.js:152

                        throw new Error("Failed generating data, no level data found");

                              ^


Error: Failed generating data, no level data found

    at /app/build/data/getMapData.js:152:31

    at step (/app/build/data/getMapData.js:33:23)

    at Object.next (/app/build/data/getMapData.js:14:53)

    at fulfilled (/app/build/data/getMapData.js:5:58)`

When using your url : http://localhost:3002/v1/map/12345/2/117/image

I got a "Server error generating map image" in Web browser and container log freeze at : 
[13.01.2022 17:03.53.239] [LOG]   Running on http://0.0.0.0:3002

[13.01.2022 17:03.57.814] [LOG]   New request for image 12345 2 117...

[13.01.2022 17:03.57.817] [LOG]   Getting single map 117

[13.01.2022 17:03.57.818] [LOG]   Spawning process: bin/d2-map.exe game --seed 12345 --difficulty 2 --map 117

**Comment by joffreybesos** [comment]
So when you do a docker exec into the container and run the command `wine bin/d2-map.exe game --seed 12345 --difficulty 1` it generates a whole bunch of JSON data?

**Comment by damienfayet** [comment]
> So when you do a docker exec into the container and run the command `wine bin/d2-map.exe game --seed 12345 --difficulty 1` it generates a whole bunch of JSON data?

Yes, inside container it's working fine, getting json data.

Even outside, I get JSON data but only once, after sending data the container close with the error message above.

**Comment by joffreybesos** [comment]
That's very strange, I don't know how that could happen even hypothetically.

But good news, I have open sourced the map server and created a new way to get the map server running.
This shouldn't need docker anymore, and should be much easier to get running.
Follow the info on this link:
https://github.com/joffreybesos/d2-mapserver/releases/tag/v1-beta

**Comment by joffreybesos** [comment]
There's actually much newer releases since https://github.com/joffreybesos/d2-mapserver/releases
Closing this issue and it should really be over there on the d2-mapserver repo.
