### ISSUE TITLE
Cow level bugging out

### ISSUE THREAD

**Issue by cocoste622** [joffreybesos/d2r-mapview#13]
everytime I enter a cow level the map would stop working properly:
I would exit and re launch the script and the problem would persist.
sometime the map would work fine but the monsters or the players dot would not be visible
some other time the map would simply not show up.
also good to note, cant interact with num pad to augment or lower the size of the map etc
this problem manifest only when I go back to town and back into the cow level

**Comment by joffreybesos** [comment]
Interesting. 
Are you running the map in 'centeredMode'?
Are you running windowed or using a multi session program at all?

Are you running in performance mode? That's my biggest suspicion.
In your settings.ini try adding `performanceMode=50ms` and see if that helps.

**Comment by cocoste622** [comment]
Im wasnt running in centeredmode,
been running it fullscreen, was working fine for few days until suddenly started to act weird
Im not sure what you mean by performance mode? are we talking about d2r setting option?
Decided to remove eevrything and re download with your new settings file, and now its working fine...

thanks for your quick reply :) and kind support Im a big fan ;)
