### ISSUE TITLE
"Invalid Option"

### ISSUE THREAD

**Issue by NAlexH2** [joffreybesos/d2r-mapview#14]
![d2rmap-v2 4 8_uxR79sr2Zi](https://user-images.githubusercontent.com/32123635/150625401-fcca87ca-6ec5-4b46-98ff-2aa12ac706f4.png)

Not quite sure what to make of this. I hit the hotkey to display whatever options while in game get this error. I'm just using it in single player since that's where I like to play if this helps at all.

EDIT: Otherwise this thing works like a dream thanks for making it :)

**Comment by joffreybesos** [comment]
Hey this has been fixed in 2.4.9. Thanks for raising this bug!
