### ISSUE TITLE
map server question

### ISSUE THREAD

**Issue by H8M3Y0** [joffreybesos/d2r-mapview#15]
Hello, ive been using the local setting on MapServer and its working great. but i was wondering if i put it on my other computer instead, how would i link the settings ini to it instead of the computer im on? ty.

**Comment by joffreybesos** [comment]
You'll just need to use the IP address of the computer that has the server running and then configure it on the other computer's settings.ini.
So `http://<IP address>:3002`

You may need to allow it through your windows firewall. I think when you first run the mapserver app it will ask if you want to allow it access to private networks, just say yes to that.

**Comment by H8M3Y0** [comment]
ok thank you
