### ISSUE TITLE
ctrl+h help menu not appearing

### ISSUE THREAD

**Issue by NAlexH2** [joffreybesos/d2r-mapview#17]
[log.txt](https://github.com/joffreybesos/d2r-mapview/files/7938057/log.txt)

Seems still unable to get ctrl+h to work in current version. Checked/deleted files and re-downloaded most current release at time of writing. Uploaded log as requested too.

**Comment by joffreybesos** [comment]
This should hopefully be fixed in 2.5.2. Could you please retest?

**Comment by NAlexH2** [comment]
I tested it and still nothing. I did notice that _briefly_ it appeared telling me to press it for help and then quickly disappeared moments later when loading into a game.

**Comment by NAlexH2** [comment]
Most recent update this is working for me, not sure about others. Really enjoy the gui settings menu too.

**Comment by CyberKnightz** [comment]
Working for me (v2.5.7)
