### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by 00mn00** [joffreybesos/d2r-mapview#20]
Any chance of implementing hidden items/caches visible on the map? Thanks for the great program, looking forward to seeing what else you do with it

**Comment by joffreybesos** [comment]
Not sure what you mean by hidden item and caches? Do you have an example?

**Comment by 00mn00** [comment]
If you look at Map Assist, for example, you'll see that hidden caches, ie things that aren't a chest, like rocks, dead rogues, etc show up on the map and then are removed after being interacted with. I was hoping you might do something like that :)

**Comment by joffreybesos** [comment]
Ah this is already implemented, rocks/dead rogues etc will show up as a chest icon on the screen, and disappear when opened.
