### ISSUE TITLE
mapview looks like its patched

### ISSUE THREAD

**Issue by morgan19779** [joffreybesos/d2r-mapview#25]
tried the new 2.8.0 beta did as instructed made offline character joined game, map didnt display in offline mode, ran around town and outside of town couldnt see any monsters/map exited game. went online selected a chacter joined a game same experience pressed \ key again no map or monsters displayed. checked link for d2mapserver as well in browser everything worked as it should.

**Comment by joffreybesos** [comment]
Should be working much better now, use 2.8.2
