### ISSUE TITLE
FPS drop with version 2.9.4

### ISSUE THREAD

**Issue by Shinnok789** [joffreybesos/d2r-mapview#29]
Hello,
Let me start by saying Thank you! for all the work put into this, it's an extremely useful tool!
It makes playing this game a LOT more enjoyable .
Now for the issue I wanted to present
Since version 2.8.8 there has been a small but visible drop in FPS while using the mapview.
Since version 2.9.4 the drop in FPS is more severe, especially during the night.
Example: while running around in the same spot, outside Lut Golhein (act 2) :
- No mapview - ~88 FPS during daylight
- Version 2.8.8 - ~84 FPS (during the night in the same spot is ~72 FPS)
- Version 2.8.9 - ~82 FPS during daylight
- Version 2.9.0 - ~80 FPS during daylight
- Version 2.9.2 - ~76 FPS during daylight
- Version 2.9.3 - ~70 FPS during daylight
- Version 2.9.4 - ~58 FPS (during the night in the same spot is ~47 FPS )
It's one exampe. In areas more loaded with enemies, it's even lower while using 2.9.4, becoming quite stressing on the eyes.
No issues encountered with 2.8.8, even on loaded areas.
Rig: CPU: Ryzen 3800X, GPU: Gigabyte Aorus RTX 2080 Super; 32GB RAM; game and map server + mapview installed on nVME SSD Adata SX8200 Pro; Windows 10 64 BIT OS.
Playing in 4K resolution, in Fullscreen mode, with DLSS active and on Quality, and using High-Very high graphics settings (only shadows on Medium).
Using mapserver V14.
For myself, for now I keep using the 2.8.8 version, it's the most buttery smooth.
But if it's possible, please fix the issue in the next versions.
Thank you again!

**Comment by joffreybesos** [comment]
Ok I think I may have improved this in 2.9.5 let me know if it's better for you
