### ISSUE TITLE
incorrect map generation

### ISSUE THREAD

**Issue by WYKDev** [joffreybesos/d2r-mapview#30]
Since the mini update few hours ago, the map generated on open areas and dungeons are wrong. Only act 2 sewer and act 3 arachnid lair are correct from I have seen.

**Comment by Krapgame** [comment]
Same for me

**Comment by hancostfu** [comment]
Same been like this sense update today

**Comment by joffreybesos** [comment]
Blizzard made an update which has broken the MH. You'll get incorrect maps for now. Please be patient while a solution is found.
A new version will be released once it's fixed. You can still see the enemy monsters and item drops in the meantime.

**Comment by Krapgame** [comment]
thanks

**Comment by hancostfu** [comment]
Thanks man

**Comment by wbslog** [comment]
thank you so much

**Comment by qkrtkdguq0** [comment]
빨리 사용 하고 싶어요

**Comment by joffreybesos** [comment]
A solution has been found, it just needs to be fully implemented and tested. I should hopefully have a release in a few hours or so.

**Comment by Krapgame** [comment]
awesome

**Comment by Kimhyeonjoung** [comment]
> 빨리 사용 하고 싶어요

애 영어를 쓰렴

**Comment by M0ndayish** [comment]
thank you so much !!

**Comment by joffreybesos** [comment]
This is now fixed. Check releases, otherwise your MH should ask to update

**Comment by Krapgame** [comment]
works awesome thanks again
