### ISSUE TITLE
Banwave here too?!

### ISSUE THREAD

**Issue by SWHSmash** [joffreybesos/d2r-mapview#32]
Hey there,
first off, thanks for creating this nice tool. :)

I heard that blizzard is doing the first huge banwave for D2R. Is your mapview also detected?

**Comment by garrand-AU** [comment]
The tool is awesome! I just want to know how this tool work before I continue to use it. 

Would you mind writing a post to explain how the tool work? How does game data flow between PC and server? I mean when I use the tool, will it cause server more work load?  

Thank you very much.

**Comment by joffreybesos** [comment]
With the June 14 ban wave it sounds like MapAssist was targeted and most d2r-mapview users were spared.
However I wouldn't interpret this as safety. It would be wise to consider d2r-mapview as the next target.
You should consider this tool detectable and I would urge people to avoid talking themselves into considering it safe.
I'll never be able to make changes that would make this tool safe from future ban waves with any real confidence.
In the meantime I'm taking some time to consider the future of this project.

**Comment by Krapgame** [comment]
I love this project!!! I hope you consider continuing it.
