### ISSUE TITLE
d2r-mapview 2.9.18 failed to open file

### ISSUE THREAD

**Issue by Xdaci** [joffreybesos/d2r-mapview#33]
Getting this error when I s/e and rejoin on my single player lk farmer. Only workaround is to restart the mapview every run, which is quite inconvenient since the runs are so fast. I tried re-setting up the server. restarting the game and the server/mapview. But same error every time, should I delete/re download? Or is it an issue with the mapview itself? Thanks for the wonderful program btw, made grinding my hc ssf char bearable after 20 years of this game lol

**Comment by joffreybesos** [comment]
Can you send a screenshot of the error? All I can suggest is make sure you have all the files from the bundle download in the wiki.

**Comment by Xdaci** [comment]
https://imgur.com/YNmzAZl

Sorry for the delayed response, my internet went out for a couple of days. Had to go out of town, and I replied in my email but not sure if it posted or not.

**Comment by Xdaci** [comment]
Yeah its weird because I was using my currently installed version fine, this error came out of nowhere. I changed literally nothing. I've been using your mapview successfully for quite some time now. Updated to many newer versions, so my map files and what not should be a non issue.

**Comment by joffreybesos** [comment]
Hmm I suspect it's having some trouble reading cached map images from your user temp folder. Very odd. I'm not even sure which error it's throwing since it seems the text is missing. Do you see anything in your log.txt when it happens?

**Comment by Xdaci** [comment]
Sorry for the delay my friend, my internet was out for 3 days. Here's the error screenshot, what makes it odd is I changed nothing. Been using this version for a bit now. Never any problems, then out of no where I get this error anytime I s/e and restart the game. On single player if that matters.
________________________________
