### ISSUE TITLE
How does d2r-mapview work?

### ISSUE THREAD

**Issue by congvmit** [joffreybesos/d2r-mapview#34]
Hello @joffreybesos,
Thank you for sharing your mapview application to d2r community.
Can you please share me the mechanism behind this mapview application?
It may be very clear if someone can read the code and try to figure out the technique under the hood. However, I cannot fully understand the whole code. 
Thank you very much.

**Comment by joffreybesos** [comment]
It leverages the fact that the random level generation is the same between old D2 LoD and D2R.
Basically, it reads from memory. It takes the mapseed which is used to generate the levels from your current game, then sends that seed to the mapserver. The mapserver does some direct dll calls to the old Diablo Lord of Destruction to generate map data. The MH then uses that data to generate a map image and shows it on screen.
Other stuff is also read from memory in real time like items, monsters, player info etc.

It only reads from memory, it doesn't write, inject dlls, or call internal game functions.
