### ISSUE TITLE
Idk what my map is supposed to look like, but surely not this lol.

### ISSUE THREAD

**Issue by Xdaci** [joffreybesos/d2r-mapview#38]
I was using a older version until today's patch which caused it to stop working. Upgraded but now when I load it and try to use my map its a huge confusing mess of a map, surely it's not supposed to look like this. 

Any way to fix this?
screenshot: https://imgur.com/1WIk8f1

**Comment by Xdaci** [comment]
I figured that may just be a in town issue but my map is also not right in dungeons. Also when I hit ctrl+H to i could not close this help screen. I had to restart the maphack to get it to close.

screenshot of map in dungeon: https://imgur.com/qjx26ZF

**Comment by Xdaci** [comment]
By the way, regardless of these current issues i wanted to thank you for the amazing maphack. I've been using it for quite some time now and gotten a lot of use out of it. Finally have my first ever ssf hc enigma, and been farming very successfully on a pitzerker thanks to the mh. Makes champ pack hunting so much easier lol. Hopefully i can get it back to working as intended so i can keep grinding.

**Comment by joffreybesos** [comment]
Going by the screenshot it seems you're using an old version of the mapserver. I recommend you download the bundle fresh from the #get-started channel on discord or from the Github wiki.

**Comment by Xdaci** [comment]
Thank you!
________________________________
