### ISSUE TITLE
malware when downloading new server?

### ISSUE THREAD

**Issue by Xdaci** [joffreybesos/d2r-mapview#40]
Upon downloading the new server I got:

Trojan:Win32/Wacatac.H!ml 

Very disappointing if this is real malware in the mapview server download as I've been using your maphack for a while now and until now would have had nothing but good things to say about it.

**Comment by joffreybesos** [comment]
Nah it's a false positive. The maphack does all sorts of things that flags on virus scanners like reading from memory and hooking global keys. This is addressed in the readme. If you aren't comfortable you can always run from the source code.

**Comment by Xdaci** [comment]
Not sure if you can even see these email responses but I did some research and did see a whole host of things can throw that exact false positive with windows. Considering I’ve been using it for quite some time and you’ve always been helpful, plus the sheer quality and amount of work you’ve clearly had to put in. All points to it in fact being a false positive, wouldn’t make much sense for you to randomly throw in a super detectable malware for no reason lol. Which btw I wasn’t even assuming it was you, but if you can’t tell in a complete layman for programming/coding. So didn’t know if it could have somehow been the upload site you use or something. Anyways I should have worded my issue more coyly. But again as a layman moon I see a pop up for a Trojan, never having heard of false positives. I freak out lol. Anyways thanks again for the help and the amazing program.

________________________________

**Comment by joffreybesos** [comment]
Np, I spoke about it in the README here https://github.com/joffreybesos/d2r-mapview#virustotal-gave-me-an-alert  
It's a common problem with game cheats.
